
language: java

sudo: false # faster builds

jdk:
  - openjdk8

env:
  global:
    - COBY_TAG_NAME: "coby"
  
script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $COBY_TAG_NAME

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ] ; then echo "travis-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER" ; else echo "travis-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER-snapshot" ; fi`
  - docker build -t $COBY_TAG_NAME . 
  - docker tag $COBY_TAG_NAME $DOCKER_USERNAME/$COBY_TAG_NAME:$TAG
  - docker push $DOCKER_USERNAME/$COBY_TAG_NAME:$TAG
  - docker tag $COBY_TAG_NAME $DOCKER_USERNAME/$COBY_TAG_NAME:latest
  - docker push $DOCKER_USERNAME/$COBY_TAG_NAME:latest
